version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      # for Home NAS
      - "8880:80"
      # for OCI
      # - "80:80"      
      - "6690:443"
    environment:
      - TZ=Asia/Seoul
      - XDG_CONFIG_HOME=/config
      - XDG_DATA_HOME=/data
    #volumes: # (for OCI)
    #  - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
    #  - /data/caddy/data:/data
    #  - /data/caddy/config:/config
    volumes: # (for Synology)
      - /volume1/docker/caddy/data:/data:rw
      - /volume1/docker/caddy/config:/config:rw
      - /volume1/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:rw
    networks:
      - reverse_proxy

  caddy-gui:
    # The image owner is now dynamically set via the REPOSITORY_OWNER environment variable for CI/CD.
    # For local development, it falls back to 'taeho9'.
    image: ghcr.io/${REPOSITORY_OWNER:-taeho9}/caddymanager/caddy-gui:latest
    container_name: caddy-gui
    restart: unless-stopped
    ports:
      - "8890:80"
    #volumes: # (for OCI)
    #  - /data/caddy/Caddyfile:/app/Caddyfile
    #  - /var/run/docker.sock:/var/run/docker.sock
    volumes: # (for Synology)
      - /volume1/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true
