version: '3.8'

services:
  caddy:
    # For local development, it falls back to 'taeho9/caddymanger'.
    image: ghcr.io/${GITHUB_REPOSITORY:-taeho9/caddymanger}/caddy-maxmind:latest
    container_name: caddy
    restart: always
    ports:
      # for Home NAS
      # - "8880:80"
      # for OCI
      - "80:80"      
      - "443:443"
    environment:
      - TZ=Asia/Seoul
      - XDG_CONFIG_HOME=/config
      - XDG_DATA_HOME=/data
    volumes: # (for OCI)
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy/data:/data
      - /data/caddy/config:/config
    # volumes: # (for Synology)
    #   - /volume1/docker/caddy/data:/data:rw
    networks:
      - reverse_proxy

  caddy-gui:
    image: ghcr.io/${GITHUB_REPOSITORY:-taeho9/caddymanger}/caddy-gui:latest
    container_name: caddy-gui
    restart: unless-stopped
    ports:
      - "8890:80"
    volumes: # (for OCI)
      - /data/caddy/Caddyfile:/app/Caddyfile
      - /var/run/docker.sock:/var/run/docker.sock
    # volumes: # (for Synology)
    #   - /volume1/docker/caddy/Caddyfile:/etc/caddy/Caddyfile

networks:
  reverse_proxy:
    name: reverse_proxy
