# This is a basic workflow to help you get started with building and pushing a Docker image.
#
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-and-push:
    # On push to main, this job builds the caddy-gui image.
    # On manual trigger (workflow_dispatch), it builds the caddy-maxmind image.

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lower case repository name
      run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Build and push caddy-gui image
      uses: docker/build-push-action@v4
      if: github.event_name == 'push'
      with:
        context: ./caddy-gui
        file: ./caddy-gui/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ env.REPO_NAME }}/caddy-gui:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push caddy-maxmind image
      uses: docker/build-push-action@v4
      if: github.event_name == 'workflow_dispatch'
      with:
        context: ./caddy_custom
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ env.REPO_NAME }}/caddy-maxmind:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
